version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab.morrison.com
    environment:
      VIRTUAL_HOST: gitlab.morrison.com
    restart: always
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

